### ISSUE TITLE
page not found.

### ISSUE THREAD

**Issue by Nutmegin** [Tangynt/Write-Side#1]
Adjusted and uploaded the files successfully according to the cmd but when I go to the site it says page not found.

Writeside.surge.sh

No idea where to begin to see what the issue is.

**Comment by Nutmegin** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose config Skipping project config: /Users/Tangynt/.npmrc. (matches userconfig)
5 verbose stack Error: Failed to parse json
5 verbose stack No value found for key version at 3:14
5 verbose stack   "version": “5.11.0”,
5 verbose stack              ^
5 verbose stack     at parseError (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
5 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)
6 verbose cwd /Users/Tangynt
7 error Darwin 15.6.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v4.5.0
10 error npm  v2.15.9
11 error file /Users/Tangynt/package.json
12 error code EJSONPARSE
13 error Failed to parse json
13 error No value found for key version at 3:14
13 error   "version": “5.11.0”,
13 error              ^
14 error File: /Users/Tangynt/package.json
15 error Failed to parse package.json data.
15 error package.json must be actual JSON, not just JavaScript.
15 error
15 error This is not a bug in npm.
15 error Tell the package author to fix their package.json file. JSON.parse
16 verbose exit [ 1, true ]
